version: '2'
services:
    baloncestoseed-app:
        image: baloncestoseed
        external_links:
            - baloncestoseed-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/baloncestoseed?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    baloncestoseed-mysql:
        extends:
            file: mysql.yml
            service: baloncestoseed-mysql
